spring:
  application:
    name: caicara-back-end
  web:
    locale: pt_BR
  datasource:
    url: "jdbc:postgresql://localhost:5432/caicara_db?useSSL=false&serverTimezone=America/Sao_paulo"
    username: docker
    password: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update